uav_names: [
  "uav1",
]

frames:
  fcu:
    publish_tf: false

uav1:

  frame: "x500"
  type: "x500"
  spawn:
    x: 0.0
    y: 0.0
    z: 0.0
    heading: 0.0

pairs_uav_flightforge_simulator:

  sensors:

    lidar:

      enabled: false

    rgb:

      enabled: false

    stereo:

      rate: 20.0

      enabled: true

      width: 640 # [px]
      height: 480 # [px]
      fov: 120.0 # [deg]

      # Left camera configuration
      left:
        offset_x: 0.3 # [m]
        offset_y: 0.0 # [m]
        offset_z: 0.0 # [m]

        rotation_pitch: 0.0 # [deg]
        rotation_yaw: 0.0 # [deg]
        rotation_roll: 0.0 # [deg]

      # Right camera configuration
      right:
        offset_x: -0.3 # [m]
        offset_y: 0.0 # [m]
        offset_z: 0.0 # [m]

        rotation_pitch: 0.0 # [deg]
        rotation_yaw: 180 # [deg]
        rotation_roll: 0.0 # [deg]

  graphics_settings: "low"

  realtime_factor: 0.5 # [-]

  # world_name: "valley" # works in Lite
  # world_name: "warehouse" # works in Lite

  # TODO
  # world_name: "cave" # does not work
  # world_name: "dead_spruce_forest" # does not work
  # world_name: "infinite_forest" # does not work
  world_name: "forest" # does not work

  # weather_type: "cloudy"

  daytime:

    hour: 15
    minute: 30
