<?xml version="1.0"?>
<package format="2">

  <name>pairs_open_vins_core</name>
  <version>1.0.0</version>
  <description>The PAIRS open_vins core metapackage</description>

  <maintainer email="canhthanh@vnu.edu.vn">Thanh Nguyen Canh</maintainer>
  <author email="canhthanh@vnu.edu.vn">Thanh Nguyen Canh</author>

  <license>BSD 3-Clause</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>cmake_modules</depend>

  <depend>ov_core</depend>
  <depend>ov_eval</depend>
  <depend>ov_init</depend>
  <depend>ov_msckf</depend>
  <depend>pairs_open_vins_estimator_plugin</depend>
  <depend>pairs_vins_kickoff_estimator_plugin</depend>
  <depend>pairs_vins_republisher</depend>
  <depend>pairs_vins_imu_filter</depend>

</package>
