<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>pairs_open_vins_core</name>
  <version>2.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="canhthanh@vnu.edu.vn">Thanh Nguyen Canh</maintainer>
  <author email="canhthanh@vnu.edu.vn">Thanh Nguyen Canh</author>

  <license>TODO: License declaration</license>

  <depend>ov_core</depend>
  <depend>ov_eval</depend>
  <depend>ov_init</depend>
  <depend>ov_msckf</depend>

  <depend>pairs_vins_imu_filter</depend>
  <depend>pairs_vins_republisher</depend>
  <depend>pairs_open_vins_estimator_plugin</depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
